name: dev

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://www.pika.dev/npm/snowpack/discuss/444
      # following step is needed because snowpack is watching files from node_modules as well
      - name: increase file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11

      - name: Cache ~/.cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-coursier-${{ hashFiles('project/Libs.scala') }}
          restore-keys: |
            ${{ runner.os }}-coursier-

      - name: Cache ~/.sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Cache ~/.npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        working-directory: ./lib
        run: npm ci

      - name: Build
        working-directory: ./lib
        run: npm run build

      - name: Unit tests
        working-directory: ./lib
        run: npm run test:unit:coverage --reporters=default --reporters=./test/testReporter.js -- append=false --output=../../RTM/testStoryMapping.txt

      - name: Integration tests
        working-directory: ./lib
        run: npm run test:integration --reporters=default --reporters=./test/testReporter.js -- append=true --output=../../RTM/testStoryMapping.txt

      - name: Build - Example App
        working-directory: ./example
        run: |
          npm ci
          npm run build

      - name: Selenium Test
        run: sbt -DgenerateStoryReport=true clean test

      - name: Generate RTM
        if: always()
        continue-on-error: true
        run: |
          ./lib/scripts/coursier launch --channel https://raw.githubusercontent.com/tmtsoftware/apps/master/apps.json rtm:d1c8c7e -- ./RTM/testStoryMapping.txt ./RTM/storyRequirementMapping.csv ./RTM/testRequirementsMapping.txt

      - name: Upload RTM
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v1
        with:
          name: RTM
          path: ./RTM

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
