name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    env:
      CSW_VERSION: "3.0.1" # Change before releasing (before tagging repo)
      ESW_VERSION: "0.2.1"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: increase file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: actions/checkout@v2
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
          apps: sbt sbtn
      - uses: coursier/cache-action@v5

      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        working-directory: ./lib
        run: npm ci

      - name: Unit tests
        working-directory: ./lib
        run: npm run test:unit:ci

      - name: Generate RTM
        if: always()
        continue-on-error: true
        run: |
          sh rtm.sh

      - name: Upload RTM to Release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            ./RTM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
