name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check library
        working-directory: ./lib
        run: |
          npm ci
          npm run build

      - name: Unit tests
        working-directory: ./lib
        run: npm run test:unit:ci

      - name: Integration tests
        working-directory: ./lib
        run: npm run test:integration:ci

      - name: Check Example App
        working-directory: ./example
        run: |
          npm ci
          npm run build

      - name: Selenium Test
        run: sbt clean test
        env:
          CSW_VERSION: "50b46f322f" # Change before releasing (before tagging repo)

      - name: Generate RTM
        if: always()
        continue-on-error: true
        run: |
          sh rtm.sh

      - name: Upload RTM
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v1
        with:
          name: RTM
          path: ./RTM

      - name: NPM Publish
        working-directory: ./lib
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Docs Publish
        run: |
          echo 'echo $GITHUB_RELEASE' > /tmp/.git-askpass
          chmod +x /tmp/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt -Dprod.publish=true clean ghpagesPushSite

        env:
          GITHUB_RELEASE: ${{ secrets.GITHUB_RELEASE }}
          GIT_ASKPASS: /tmp/.git-askpass

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
